version: '3'
services:

  WikipediaOffline:
    image: wiki-fr-img
    ports:
    - "8080:80"
    restart: always
    
  KhanAcademy:
    image: quantumobject/docker-ka-lite
    ports:
    - "8081:8008"
    restart: always

  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
    restart: always
  Moodle:
    image: 'bitnami/moodle:3'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8083:80'
      - '443:443'
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - mariadb
    restart: always
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
        
