version: "3.3"


services:
  # Simple landing page
  web:
    build: 
      context: ./submodules/web
      dockerfile: Dockerfile
    networks:
      - internal
      - external
    ports: 
      - "8000:8000"

  # Dump dns server that hijack
  dns-hijack:
    build:
      context: ./submodules/dns
      dockerfile: Dockerfile
    ports:
      - "5354:53/udp"
    networks:
      - internal
      - external

  # Data base of users
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - internal
    restart: always
    volumes:
      - "./db:/var/lib/postgresql/data"


networks:
  # Internal conection between services
  internal:
    driver: bridge
    internal: true

  # Conection with the outside
  external:
    driver: bridge
