version: '3'
services:

  WikipediaOffline:
    image: wiki-fr-img
    ports:
            - "127.0.0.1:8080:80"
    restart: always
    
    #  KhanAcademy:
    #    image: quantumobject/docker-ka-lite
    #    ports:
    #            - "127.0.0.1:8082:8008"
    #    restart: always

  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MOODLE_SITENAME=http://moodle.dks
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
    restart: always
  Moodle:
    image: 'bitnami/moodle:3'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=dks
      - MOODLE_PASSWORD=origineYEUMBEUL
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
            - '8081:80'
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - mariadb
    restart: always
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
        
