# Generated by Django 3.1.12 on 2021-07-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registre',
            fields=[
                ('ip', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('registrat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('edat', models.IntegerField()),
                ('sexe', models.CharField(max_length=100)),
                ('resideix_a', models.CharField(max_length=100)),
                ('registrat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
